apiVersion: v2
name: financial-budget
description: A Helm chart for Financial Budget
version: 0.8.0
appVersion: "67fd03d8bcb75572f7cc432865dc9cb007858e69"
dependencies:
  - name: postgresql
    version: 15.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 19.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: replicated
    alias: financial-budget-sdk
    version: 1.19.3
    repository: oci://registry.replicated.com/library
