apiVersion: v2
name: financial-budget
description: A Helm chart for Financial Budget
version: 0.14.0
appVersion: "460ab9c5e7f8114e4cc3f59ee1cc25ef0b986599"
dependencies:
  - name: postgresql
    version: 15.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 19.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: replicated
    alias: financial-budget-sdk
    version: 1.19.3
    repository: oci://registry.replicated.com/library
