apiVersion: v2
name: financial-budget
description: A Helm chart for Financial Budget
version: 0.65.0
appVersion: "e459833455e4e01325a8617433eb55439ac3f9ed"
dependencies:
  - name: postgresql
    version: 15.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 19.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: replicated
    alias: financial-budget-sdk
    version: 1.19.3
    repository: oci://registry.replicated.com/library
