{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) }}
{{- $cert := genSelfSignedCert "financial-budget.local" nil nil 365 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "financial-budget.fullname" . }}-tls
  labels:
    {{- include "financial-budget.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
