apiVersion: v2
appVersion: f11f5b8ae10e83d977979c778f468c10ffdddef8
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 15.5.0
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 19.6.0
- alias: financial-budget-sdk
  name: replicated
  repository: oci://registry.replicated.com/library
  version: 1.19.3
description: A Helm chart for Financial Budget
name: financial-budget
version: 0.28.0
