apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: financial-budget
spec:
  title: Financial Budget
  icon: https://raw.githubusercontent.com/osc135/financial-budget/main/replicated/icon.png
  statusInformers:
    - deployment/financial-budget-backend
    - deployment/financial-budget-frontend
    - statefulset/financial-budget-postgresql
    - statefulset/financial-budget-redis-master
    - deployment/financial-budget-sdk
  ports:
    - serviceName: ingress-nginx-controller
      servicePort: 80
      localPort: 8080
      applicationUrl: http://ingress-nginx-controller
